change fluentd helm chart

diff --git a/helm/elastic-stack-app/charts/fluentd-elasticsearch/values.yaml b/helm/elastic-stack-app/charts/fluentd-elasticsearch/values.yaml
--- a/helm/elastic-stack-app/charts/fluentd-elasticsearch/values.yaml
+++ b/helm/elastic-stack-app/charts/fluentd-elasticsearch/values.yaml
@@ -3,7 +3,7 @@ image:
 ## Specify an imagePullPolicy (Required)
 ## It's recommended to change this to 'Always' if the image tag is 'latest'
 ## ref: http://kubernetes.io/docs/user-guide/images/#updating-images
-  tag: v2.7.0
+  tag: v2.8.0
   pullPolicy: IfNotPresent
   ## Optionally specify an array of imagePullSecrets.
   ## Secrets must be manually created in the namespace.
@@ -17,6 +17,16 @@ image:
 ## proxy that takes care of signing all requests being sent to the AWS ES Domain.
 awsSigningSidecar:
   enabled: false
+  resources: {}
+  # limits:
+  #   cpu: 100m
+  #   memory: 500Mi
+  # requests:
+  #   cpu: 100m
+  #   memory: 200Mi
+  network:
+    port: 8080
+    address: localhost
   image:
     repository: abutaha/aws-es-proxy
     tag: 0.9
@@ -36,13 +46,13 @@ hostLogDir:
 ## Configure resource requests and limits
 ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
 ##
-resources:
-  limits:
-    cpu: 100m
-    memory: 500Mi
-  requests:
-    cpu: 100m
-    memory: 200Mi
+resources: {}
+  # limits:
+  #   cpu: 100m
+  #   memory: 500Mi
+  # requests:
+  #   cpu: 100m
+  #   memory: 200Mi
 
 elasticsearch:
   auth:
@@ -51,8 +61,8 @@ elasticsearch:
     password: "yourPass"
   bufferChunkLimit: "2M"
   bufferQueueLimit: 8
-  host: "elasticsearch-master"
-  logstashPrefix: "fluentd"
+  host: "elasticsearch-client"
+  logstashPrefix: "logstash"
   port: 9200
   path: ""
   scheme: "http"
@@ -94,12 +104,13 @@ serviceAccount:
   # The name of the ServiceAccount to use.
   # If not set and create is true, a name is generated using the fullname template
   name: ""
+  annotations: {}
 
 ## Specify if a Pod Security Policy for node-exporter must be created
 ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
 ##
 podSecurityPolicy:
-  enabled: true
+  enabled: false
   annotations: {}
     ## Specify pod annotations
     ## Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#apparmor
@@ -114,27 +125,37 @@ livenessProbe:
   enabled: true
   initialDelaySeconds: 600
   periodSeconds: 60
-  command:
-  - '/bin/sh'
-  - '-c'
-  - >
-    LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300};
-    STUCK_THRESHOLD_SECONDS=${STUCK_THRESHOLD_SECONDS:-900};
-    if [ ! -e /var/log/fluentd-buffers ];
-    then
-      exit 1;
-    fi;
-    touch -d "${STUCK_THRESHOLD_SECONDS} seconds ago" /tmp/marker-stuck;
-    if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-stuck -print -quit)" ];
-    then
-      rm -rf /var/log/fluentd-buffers;
-      exit 1;
-    fi;
-    touch -d "${LIVENESS_THRESHOLD_SECONDS} seconds ago" /tmp/marker-liveness;
-    if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-liveness -print -quit)" ];
-    then
-      exit 1;
-    fi;
+  kind:
+    exec:
+      command:
+      # Liveness probe is aimed to help in situations where fluentd
+      # silently hangs for no apparent reasons until manual restart.
+      # The idea of this probe is that if fluentd is not queueing or
+      # flushing chunks for 5 minutes, something is not right. If
+      # you want to change the fluentd configuration, reducing amount of
+      # logs fluentd collects, consider changing the threshold or turning
+      # liveness probe off completely.
+      - '/bin/sh'
+      - '-c'
+      - >
+        LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300};
+        STUCK_THRESHOLD_SECONDS=${STUCK_THRESHOLD_SECONDS:-900};
+        if [ ! -e /var/log/fluentd-buffers ];
+        then
+          exit 1;
+        fi;
+        touch -d "${STUCK_THRESHOLD_SECONDS} seconds ago" /tmp/marker-stuck;
+        if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-stuck -print -quit)" ];
+        then
+          rm -rf /var/log/fluentd-buffers;
+          exit 1;
+        fi;
+        touch -d "${LIVENESS_THRESHOLD_SECONDS} seconds ago" /tmp/marker-liveness;
+        if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-liveness -print -quit)" ];
+        then
+          exit 1;
+        fi;
+
 annotations: {}
 
 podAnnotations: {}
@@ -146,7 +167,7 @@ podAnnotations: {}
 updateStrategy:
   type: RollingUpdate
 
-tolerations: {}
+tolerations: []
   # - key: node-role.kubernetes.io/master
   #   operator: Exists
   #   effect: NoSchedule
@@ -176,6 +197,14 @@ serviceMonitor:
   path: /metrics
   port: 24231
   labels: {}
+  metricRelabelings: []
+  relabelings: []
+
+serviceMetric:
+  ## If true, the metrics service will be created
+  ## Alternative to implicit creation through serviceMonitor.enabled
+  ##
+  enabled: false
 
 prometheusRule:
   ## If true, a PrometheusRule CRD is created for a prometheus operator
@@ -190,24 +219,25 @@ configMaps:
   useDefaults:
     systemConf: true
     containersInputConf: true
-    systemInputConf: false
-    forwardInputConf: false
-    monitoringConf: false
+    systemInputConf: true
+    forwardInputConf: true
+    monitoringConf: true
     outputConf: true
 
 # can be used to add new config or overwrite the default configmaps completely after the configmaps default has been disabled above
-extraConfigMaps:
+extraConfigMaps: {}
   # system.conf: |-
   #   <system>
   #     root_dir /tmp/fluentd-buffers/
   #   </system>
 
-# extraVolumes:
+extraVolumes: []
 #   - name: es-certs
 #     secret:
 #       defaultMode: 420
 #       secretName: es-certs
-# extraVolumeMounts:
+
+extraVolumeMounts: []
 #   - name: es-certs
 #     mountPath: /certs
 #     readOnly: true
